#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十 

bspc config border_width         6
bspc config window_gap          24

bspc config normal_border_color '#333333'
bspc config active_border_color '#333333'
bspc config focused_border_color '#888888'

bspc config focus_follows_pointer true
bspc config unclutter -idle 3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zen desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a legcord desktop='^2'
bspc rule -a Alacritty desktop='^3'
bspc rule -a steam desktop='^4'
bspc rule -a Gimp desktop='^8'
bspc rule -a Spotify desktop='^9'

$HOME/.config/bspwm/bspwm.d/autostart.sh
